let n1 = parseFloat(prompt("Informe o 1º número: "));
let n2 = parseFloat(prompt("Informe o 2º número: "));
let soma = n1 + n2;
let sub = n1 - n2;
let mult = n1 * n2;
let div = n1 / n2;
console.log("Soma: " + soma);
console.log("Subtração: " + sub);
console.log("Multiplicação: " + mult);
console.log("Divisão: " + div);